name: maccies_timetable
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dependencies:
  html: ^0.15.0
  ical: ^0.1.4
